image: pulshashi/builder:gradle-npm-latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd $CI_PROJECT_DIR/ips
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - gradle --build-cache build
    - gradle sonarqube -x test -Dsonar.projectKey=ips -Dsonar.host.url=http://apps-sonarqube-sonarqube:9000 -Dsonar.login=ad7a797ba98292f1e74c891bcd8c89e0f2b7cc67 --stacktrace
    - gradle artifactoryPublish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

sonar-ts:
  image: sonarsource/sonar-scanner-cli
  stage: build
  variables:
    SONAR_HOST_URL: 'http://apps-sonarqube-sonarqube:9000'
    SONAR_TOKEN: 'ad7a797ba98292f1e74c891bcd8c89e0f2b7cc67'
  script:
    - cd $CI_PROJECT_DIR/ips/ips-simulator-web/src/main/ts
    - sonar-scanner -Dsonar.projectKey=ips-ui -Dsonar.sources=./src/iochord -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

stop:
  image: lwolf/helm-kubectl-docker:v152_213
  stage: build
  script:
    - echo Stopping current service ...
    - kubectl scale --replicas=0 statefulset/apps-ips-spring-runner
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

start:
  image: lwolf/helm-kubectl-docker:v152_213
  stage: deploy
  script:
    - echo Starting service ...
    - kubectl scale --replicas=1 statefulset/apps-ips-spring-runner
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
