image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd $CI_PROJECT_DIR/chdsr
  - export GRADLE_USER_HOME=`pwd`/.gradle
      
run:
  stage: deploy
  script:
    - kubectl scale --replicas=0 statefulset/apps-chdsr
    - kubectl scale --replicas=1 statefulset/apps-chdsr
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
