image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd $CI_PROJECT_DIR/chdsr
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
build:
  stage: build
  script: gradle --build-cache build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

deploy:
  stage: build
  script:
    - gradle jar  
    - gradle artifactoryPublish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle