image: pulshashi/builder:gradle-npm-latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - cd $CI_PROJECT_DIR/ips
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: 
    - tar -czvf ips-phyton-analysis-0.0.1-SNAPSHOT.tgz $CI_PROJECT_DIR/ips/ips-phyton-analysis/src/main/python
    - curl -X PUT -u admin:password -T ips-phyton-analysis-0.0.1-SNAPSHOT.tgz "http://artifactory.tips.iochord.co.kr/artifactory/generic-local/io/iochord/apps/ips/ips-phyton-analysis-0.0.1-SNAPSHOT.tgz"
    - gradle --build-cache build
    - gradle sonarqube -x test -Dsonar.projectKey=ips -Dsonar.host.url=http://apps-sonarqube-sonarqube:9000 -Dsonar.login=772e702bc2406c2c88573c4cf76481fb739a137a --stacktrace
    - gradle artifactoryPublish
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

sonar-ts:
  image: sonarsource/sonar-scanner-cli
  stage: build
  variables:
    SONAR_HOST_URL: 'http://apps-sonarqube-sonarqube:9000'
    SONAR_TOKEN: '772e702bc2406c2c88573c4cf76481fb739a137a'
  script:
    - cd $CI_PROJECT_DIR/ips/ips-simulator-web/src/main/ts
    - sonar-scanner -Dsonar.projectKey=ips-ui -Dsonar.sources=./src/iochord -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN

stop:
  image: lwolf/helm-kubectl-docker:v152_213
  stage: build
  script:
    - echo Stopping current service ...
    - kubectl scale --replicas=0 statefulset/apps-ips-spring-runner
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

start:
  image: lwolf/helm-kubectl-docker:v152_213
  stage: deploy
  script:
    - echo Starting service ...
    - kubectl scale --replicas=1 statefulset/apps-ips-spring-runner
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
