@startuml "Login"
actor User
boundary "Login Page \n(AuthenticationLoginView.vue)" as login
boundary "Home Page \n(HomeView.vue)" as home

control "Validates login data" as c1
control "Display Home page" as c2
control "Display Login page with error" as c3 #red
control "Display Logout page" as c4

entity "User Accounts" as user

User -> login

login -> c1 : enter email and password then "login()"

c1 -> user
activate user
|||
alt "email && password !== null"
user --> c2
c2 --> home
else "email || password === null"
user --> c3
deactivate user
c3 --> login
end

home -> c4 : "logout()"
activate c4
|||
c4 --> login
deactivate c4

@enduml
