@startuml "Register"
actor User
boundary "Login Page" as login
boundary "Home Page" as home
boundary "Register Page" as register

control "Display Register page" as c1
control "Validates register data" as c2
control "Display Register page with error" as c3 #red
control "Display Login page" as c4

entity "User Accounts" as user

User -> login

login -> c1
activate c1
|||
c1 --> register
deactivate c1

register -> c2 : enter registration data and "register()"

c2 -> user
activate user

alt "email === null"
user --> c4
c4 --> login
else "email !== null"
user --> c3
deactivate user
c3 --> register
end

@enduml
