@startuml "Change Node Properties"

actor User
boundary "Canvas Component  \n(CanvasComponent.vue)" as editor
control "Display node / data node modal \n(...Modal.vue)" as c1
control "Save model" as c2

entity "Simulation model" as e1

User -> editor

editor -> c1 : "element:pointerdblclick(elementView)"
activate c1
c1 -> c1 : "populateProperties(page, object)"
activate c1

c1 -> c2 : "saveProperties(page, object)"
deactivate c1

c2 -> e1
activate e1
|||
e1 --> c1
deactivate c1
deactivate e1

c1 --> editor

@enduml
