@startuml "Delete Nodes / Data"

actor User

boundary "CanvasComponent.vue" as c


control "Highlight element(s)" as c0
control "Display list of depended node/data modal\n(DeleteModals.vue)" as c1
control "Update Canvas" as c2
control "Save model" as c3

entity "Simulation Model" as e1

User -> c

activate c
c -> c0 : "element:pointerclick(elementView)"
c0 -> c1 : "document.addEventListener('keydown', (e) => { \n\tswitch (e.which) { \n\t\t// Backspace & Delete key \n\t\tcase 8: case 46: \n\t\t\t...\n\t\t\tDeletableModal.populateNode(node)\n\t\t\t...\n\t}\n}"

c1 -> c2 : "resetFields()"
c2 -> c3
activate c3
c3 -> e1
activate e1
|||
e1 --> c3
deactivate c3
deactivate e1
c3 --> c
deactivate c
@enduml
