@startuml "Manage Data Source"
left to right direction

actor :User: as user
rectangle "Manage Data Source" {
  ' User may connect to data source
  user -- (Create new connection)
  (Create new connection) <.. (List connection) : <<extends>>
  (Create new connection) <.. (Connect to Oracle database) : <<extends>>
  (Create new connection) <.. (Connect to MSSQL database) : <<extends>>
  (Create new connection) <.. (Connect to MySQL database) : <<extends>>
  (Create new connection) <.. (Connect to Hadoop file system) : <<extends>>

  (Set connection name) <.. (Create new connection) : <<includes>>
  (Configure database or connection properties) <.. (Create new connection) : <<includes>>
  (Set authentication properties) <.. (Create new connection) : <<includes>>


  ' Custom information for Oracle connection
  (Connect to Oracle database) <.. (Filter Query) : <<extends>>
  (Filter Query) ..> (Preview Query) : <<includes>>

  ' Custom information for MySQL connection
  (Connect to MySQL database) <.. (Configure SSL options) : <<extends>>
  (Connect to MySQL database) <.. (Set proxy) : <<extends>>

  ' Or import event log data
  user -- (Import file)
  (Import file) <.. (Import CSV) : <<extends>>
  (Import file) <.. (Import XES) : <<extends>>
  (Import file) <.. (Import MXML) : <<extends>>
  (Import file) <.. (Import simulation model) : <<extends>>
  (Import file) <.. (Import CPN) : <<extends>>
  (Import file) <.. (Import process model) : <<extends>>
}
@enduml
