@startuml "Package Diagram"
left to right direction

package "iochord/ips" {
  package "analysis" {
    package "process discovery"
    package "branch mining"
    package "resource mining"
    package "distribution fitting"
    file "AnalysisRouter.ts"
  }

  package "common" {
    package "browser"
    package "charts"
    package "graph"
    package "kpi"
    package "logging"
    package "semantic"
    package "service"
    package "ui"
  }

  package "data" {
    package "connection"
    package "filter"
    package "mapping"
    package "history / browser"
    file "DataRouter.ts"
  }

  package "model (simulation)" {
    package "editor"
    package "generator"
    file "SimulationRouter.ts"
  }

  package "sandbox"

  package "web" {
    package "Home"
    package "User"
    file "WebRouter.ts"
  }

  file "IpsRouter.ts"
}

file "main.ts"
file "router.ts"
@enduml
