@startuml "Perform Event Log Analysis"
left to right direction

actor :User: as user
rectangle "Perform Event Log Analysis" {
  package "Process Model Discovery" {
    user -- (Mine process model)
    (Mine process model) <.. (Mine process model using Heuristic Miner) : <<extends>>
    (Mine process model) .> (Set parameter): <<includes>>
  }

  package "Branch Mining" {
    user -- (Mine branches)
    user -- (View mined branches)
    (Mine branches) ..> (Select branch miner algorithm) : <<includes>>
  }

  package "Resource Mining" {
    user -- (Mine resources)
    user -- (View mined resources)
    (Mine resources) ..> (Select resource miner algorithm) : <<includes>>
  }

  package "Distribution Fitting" {
    user -- (Perform distribution fitting)
    user -- (View distribution fitting result)
    (Perform distribution fitting) ..> (Select distribution fitting algorithm) : <<includes>>
  }
}
@enduml
