@startuml "Create Simulation Model"

actor User
boundary "Editor page \n(SimulationEditorView.vue)" as editor
control "Create new blank canvas" as c1

User -> editor

editor -> c1 : "modelCreate()"
activate c1
|||
c1 --> editor
deactivate c1

@enduml
